$NetBSD: patch-Cargo.toml,v 1.1 2023/01/12 12:55:46 pin Exp $

Don't patch crate, only needed for cross-compilling.
See, https://github.com/kornelski/rust-ffmpeg-sys-1/commit/78458039d5fac99354f9cb078869f3be3f3af5fb

--- Cargo.toml.orig	2022-12-04 00:18:07.000000000 +0000
+++ Cargo.toml
@@ -85,6 +85,6 @@ strip = true
 
 [package.metadata.docs.rs]
 targets = ["x86_64-unknown-linux-gnu"]
-
-[patch.crates-io]
-ffmpeg-sys-next = { rev = "78458039d5fac99354f9cb078869f3be3f3af5fb", git = "https://github.com/kornelski/rust-ffmpeg-sys-1"}
+#
+#[patch.crates-io]
+#ffmpeg-sys-next = { rev = "78458039d5fac99354f9cb078869f3be3f3af5fb", git = "https://github.com/kornelski/rust-ffmpeg-sys-1"}
