$NetBSD: patch-Cargo.toml,v 1.7 2023/01/11 03:33:46 tnn Exp $

Comment out unpublished test dependency

--- Cargo.toml.orig	2023-01-05 17:41:15.000000000 +0000
+++ Cargo.toml
@@ -51,5 +51,5 @@ askama = "0.11.1"
 pgx-tests = "0.6.1"
 
 # from e2e workspace
-test-generator = { git = "https://github.com/JamesGuthrie/test-generator" }
+#test-generator = { git = "https://github.com/JamesGuthrie/test-generator" }
 test-common = { path = "./test-common" }
